server:
  port: 443
  ssl:
    key-store: server.keystore
    key-alias: tomcat
    enabled: true
    key-store-password: lwj000720
    key-store-type: JKS
  servlet:
    context-path: /szpd
spring:
  jackson:
    serialization:
      indent_output: true
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
  mvc:
    throw-exception-if-no-handler-found: true
  resources:
    add-mappings: false
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/szpd?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: lwj000720
    initialSize: 5
    minIdle: 5
    maxWait: 60000
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECT 1 FROM DUAL
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 20
    filters: stat,wall,log4j
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000

mybatis:
  type-aliases-package: com.liwj.szpd.model
  config-locations: classpath:mybatis/mybatis-config.xml
  mapper-locations: classpath:mybatis/mapper/*.xml


pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  autoRuntimeDialect: true
  rowBoundsWithCount: true
  offsetAsPageNum: true